#!/usr/bin/env python3
"""
sparsify_moe_trace.py
────────────────────────────────────────────────────────────────────────────
Reads the 5-column MoE Batch Trace CSV generated by score_collect.py:
    query_id, token_id, layer_id, experts, attention

For each sparsity value *s* (e.g., 20 -> drop bottom 20%), it generates
a new CSV file where the 'attention' list keeps only the top (100-s)%
of indices. The 'experts' column and others are preserved exactly.

Output files follow the naming convention:
    <input_basename>_<s>.csv
────────────────────────────────────────────────────────────────────────────
Usage:
    python sparsify_moe_trace.py <input_csv> <s1> <s2> ...
    
Example:
    python sparsify_moe_trace.py mixtral_batch_trace.csv 20 50 80
    # Generates: mixtral_batch_trace_20.csv, mixtral_batch_trace_50.csv, etc.
"""

import csv
import json
import math
import os
import sys
from typing import List, Dict, IO

# Increase field size limit for large attention lists
csv.field_size_limit(sys.maxsize)

def _open_writers(input_path: str, sparsities: List[int]) -> Dict[int, IO]:
    """Create one CSV writer per sparsity value."""
    base, ext = os.path.splitext(input_path)
    writers = {}
    for s in sparsities:
        out_path = f"{base}_{s}{ext}"
        fh = open(out_path, "w", newline="")
        writer = csv.writer(fh)
        # Write the 5-column header expected by TraceReader
        writer.writerow(["query_id", "token_id", "layer_id", "experts", "attention"])
        writers[s] = (writer, fh)
    return writers

def sparsify_moe_csv(input_csv: str, sparsities: List[int]) -> None:
    """
    Parameters
    ----------
    input_csv : str
        Path to the full-attention MoE trace CSV.
    sparsities : List[int]
        List of integers representing the percentage of attention tokens to DROP.
        (e.g., 20 means keep top 80%).
    """
    if not sparsities:
        raise ValueError("Sparsities list cannot be empty.")

    print(f"Processing {input_csv} for sparsities: {sparsities}...")
    writers = _open_writers(input_csv, sparsities)

    with open(input_csv, newline="") as fin:
        reader = csv.DictReader(fin)
        
        # Validate headers roughly match expected format
        fieldnames = reader.fieldnames
        if not fieldnames or "attention" not in fieldnames:
            print("Warning: Input CSV headers might be missing or incorrect. "
                  "Expected 'attention' column.")

        count = 0
        for row in reader:
            # 1. Parse Columns (Flexible get for slightly different naming conventions)
            qid = row.get("query_id") or row.get("query_num")
            tid = row.get("token_id") or row.get("absolute_token_index")
            lid = row.get("layer_id") or row.get("layer_num")
            
            # Experts and Attention are stored as JSON lists
            experts_raw = row.get("experts") or row.get("used_expert_indices")
            attn_raw = row.get("attention") or row.get("token_indices_by_attention")

            try:
                # We don't need to parse experts, just pass the string through
                # But parsing confirms validity.
                # experts = json.loads(experts_raw) 
                
                # We MUST parse attention to slice it
                attn_indices = json.loads(attn_raw)
            except (json.JSONDecodeError, TypeError):
                print(f"Skipping malformed row {count}: {row}")
                continue

            L = len(attn_indices)

            # 2. Write to each sparsity file
            for s in sparsities:
                # Calculate keep ratio
                keep_frac = 1.0 - (s / 100.0)
                
                if L > 0:
                    # Calculate number of tokens to keep (ceiling ensures we don't drop everything if L is small)
                    k = max(1, int(math.ceil(L * keep_frac)))
                    # Slice the top-k indices
                    kept_indices = attn_indices[:k]
                else:
                    kept_indices = []

                writer, _ = writers[s]
                
                # Write row: qid, tid, lid, experts (unchanged), kept_attention (json dumped)
                writer.writerow([
                    qid, 
                    tid, 
                    lid, 
                    experts_raw,  # Write original experts string to avoid re-serialization issues
                    json.dumps(kept_indices)
                ])
            
            count += 1
            if count % 1000 == 0:
                print(f"Processed {count} rows...", end="\r")

    # Close all files
    for _, fh in writers.values():
        fh.close()

    print(f"\nFinished! Generated {len(sparsities)} sparsified trace files.")

if __name__ == "__main__":
    if len(sys.argv) < 3:
        print(
            "USAGE: python sparsify_moe_trace.py <input_csv> <sparsity_1> [<sparsity_2> ...]\n"
            "EXAMPLE: python sparsify_moe_trace.py mixtral_batch_trace.csv 20 80 95",
            file=sys.stderr,
        )
        sys.exit(1)

    in_csv = sys.argv[1]
    # Parse remaining args as integers
    spars_list = [int(x) for x in sys.argv[2:]]
    
    if not os.path.exists(in_csv):
        print(f"Error: Input file '{in_csv}' not found.")
        sys.exit(1)

    sparsify_moe_csv(in_csv, spars_list)